# Generated by Django 5.0 on 2024-03-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_category_product_review_shop_product_shop_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='reviewer',
        ),
    ]
