# Generated by Django 5.0 on 2024-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_alter_inventory_product_alter_inventory_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('null', 'Null'), ('cart', 'Cart'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='null', max_length=10, verbose_name='status'),
        ),
    ]
