# Generated by Django 5.0 on 2024-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_alter_inventory_product_alter_inventory_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('confirmed', 'confirmed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='cart', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('owner', 'owner'), ('buyer', 'buyer'), ('seller', 'seller')], default='buyer', max_length=10, verbose_name='role'),
        ),
    ]
