# Generated by Django 5.0.3 on 2024-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('confirmed', 'confirmed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='confirmed', max_length=10, verbose_name='status'),
        ),
    ]
